Add Story and create materials storybook folder
axa-ch/patterns-library pull request #1581
Opened 2020-01-03 15:18 UTC by danyball

Fixes #429 

# Done is when (DoD):
- [ ] I have added UI/Unit tests for my changes
- [ ] I added modified component properties to the typescript typings
- [ ] Design has been reviewed with (here name of reviewer)
- [ ] My changes are accordingly to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)
- [ ] Old tests and eslint rule are not broken
- [ ] My changes are well documented in the README and showcased in the stories 
- [ ] Tested with IE

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (focus on **WHY**)
- [ ] I have made/updated the ChangeLog Section in the README

2020-01-06 11:40 UTC, 01231 reviewed
Have you seen the link in the story from andy? I like it and I think it would fit good into the pattern-library.
https://design.axa.com/toolkit/v2/getting-started/colors.html

2020-01-06 12:14 UTC, danyball commented
> Have you seen the link in the story from andy? I like it and I think it would fit good into the pattern-library.
> https://design.axa.com/toolkit/v2/getting-started/colors.html

Yes thats nice. I am doing some replaces on "scss string" to color each line. For me it was too expansive to beautify it like andys link. 

New ticket or invest some more time for that in this PR?

2020-01-07 10:39 UTC, danyball commented
Load scss dynamically and make it more beatifuly like noahs link,.

2020-01-10 10:16 UTC, danyball commented
Load scss variables with webpack:
'to-string-loader' must be replaced by "style-loader. Problem.

2020-01-22 07:49 UTC, danyball commented
PR ist soweit fertig. Dynamisches laden von SCSS Code als Text habe ich nicht hinbekommen - ist aber auch kein nogo würde ich sagen.

2020-01-22 08:29 UTC, 01231 requested changes
would be nice if all boxes are aligned
![Screenshot 2020-01-22 at 09 29 06](https://user-images.githubusercontent.com/38284563/72877650-ab7f6e80-3cf9-11ea-920b-2710245efadf.png)

2020-01-22 08:33 UTC, 01231 requested changes

2020-01-22 08:33 UTC, NoahLiechti commented on src/components/00-materials/styles/story.js
> +/// main palette colors (excluding brand colors)
make all headings uppercase

2020-01-22 08:33 UTC, NoahLiechti commented on src/components/00-materials/styles/story.js
> +/// secondary palette
dito

2020-01-22 08:33 UTC, NoahLiechti commented on src/components/00-materials/styles/story.js
> +/// main palette colors (excluding brand colors)
dito

2020-01-22 08:33 UTC, NoahLiechti commented on src/components/00-materials/styles/story.js
> +/// secondary palette
dito

2020-01-22 08:35 UTC, raphaellueckl commented
<img width="1086" alt="Screenshot 2020-01-22 at 09 29 18" src="https://user-images.githubusercontent.com/8248662/72878040-7889aa80-3cfa-11ea-99fa-d10efb205b7c.png">

Here is my review

2020-01-22 09:13 UTC, NoahLiechti commented
@raphaellueckl as far as I have seen the <axa-text> doesn't work and we have to fix this bug first before we can use <axa-text> here

2020-01-22 09:53 UTC, danyball commented
> @raphaellueckl as far as I have seen the doesn't work and we have to fix this bug first before we can use here

I put font-familiy to the body css. That works.

2020-01-22 10:00 UTC, raphaellueckl commented
Hier noch ein paar Vorschläge:

```
.colorwrapper {
    ...
    display: flex;
    flex-direction: column;
    align-items: center;
}

.colorvisualisation {
margin-bottom: 10px;
}

body {
font-family: Source Sans Pro,Arial,sans-serif;
}


```

Führt zu folgendem Resultat:

<img width="853" alt="Screenshot 2020-01-22 at 10 59 27" src="https://user-images.githubusercontent.com/8248662/72884365-4d0cbd00-3d06-11ea-8fd1-38f8f5b18e7e.png">

2020-01-22 16:43 UTC, raphaellueckl commented on src/components/00-materials/styles/story.js
> +/// AXA brand colors
Three slashes?

2020-01-22 16:43 UTC, raphaellueckl approved these changes

2020-01-22 17:16 UTC, 01231 approved these changes

2020-01-23 08:28 UTC, merged