Bugfix/datepicker
axa-ch/patterns-library pull request #1608
Opened 2020-01-14 07:28 UTC by danyball

Fixes #1601

# Done is when (DoD):
- [ ] I have added UI/Unit tests for my changes
- [ ] Old tests and eslint rule are not broken
- [ ] I added modified component properties to the typescript typings
- [ ] Design has been reviewed with (here name of reviewer)
- [ ] My changes are accordingly to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)
- [ ] My changes are well documented in the README and showcased in the stories 
- [ ] My changes are shortly added to CHANGELOG.md with the issue number
- [ ] Tested with IE

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (focus on **WHY**)
- [ ] I have made/updated the ChangeLog Section in the README

2020-01-14 13:46 UTC, raphaellueckl submitted a review, later dismissed
lgtm

2020-01-15 13:44 UTC, markus-walther requested changes
Looks good to me, 2 minor doc changes as discussed.

2020-01-15 13:44 UTC, markus-walther commented on src/components/20-molecules/datepicker/CHANGELOG.md
> +- Set a width to popup wrapper because of IE (Issue #1601)
Wording: Changed implementation internals for `width` due to IE bug (#1601).

2020-01-15 13:44 UTC, markus-walther commented on src/components/20-molecules/datepicker/CHANGELOG.md
> +- We do not set height to component anymore because that causes a bad behavior if you has set a label text
Wording: component `height` implementation internals changed.

2020-01-22 10:54 UTC, merged