Remove forced imported components
axa-ch/patterns-library pull request #1632
Opened 2020-01-23 09:34 UTC by LucaMele

Fixes #(issue).

# Done is when (DoD):
- [ ] I have added UI/Unit tests for my changes
- [ ] Old tests and eslint rule are not broken
- [ ] I added modified component properties to the typescript typings
- [ ] Design has been reviewed with (here name of reviewer)
- [ ] My changes are accordingly to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)
- [ ] My changes are well documented in the README and showcased in the stories 
- [ ] My changes are shortly added to CHANGELOG.md with the issue number
- [ ] Tested with IE

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (focus on **WHY**)

2020-01-27 08:59 UTC, markus-walther requested changes
Nice! Some small findings, no biggies.

I would hope you could also adapt create-a-m-o and the package.json template.

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/postbuild.js
> +
Please document purpose/rationale for this file

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/postbuild.js
> +const pkgPath = `${process.cwd()}/package.json`;
DRYify process.cwd()

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/postbuild.js
> +fs.copyFileSync(pkgPathTmp, pkgPath);
file ops can always fail, since you're not the exclusive owner of the file system - guard against failure here and elsewhere

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/prebuild.js
> +
Please document purpose/rationale for this file

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/prebuild.js
> +const pkgPath = `${process.cwd()}/package.json`;
DRYify process.cwd()

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/prebuild.js
> +fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
missing newline

2020-01-27 08:59 UTC, markus-walther commented on scripts/build/postbuild.js
> +fs.unlinkSync(pkgPathTmp);
missing newline

2020-01-31 09:55 UTC, LucaMele commented
replaced with #1646

2020-01-31 09:55 UTC, closed without merging