remove browser default margins for axa-heading
axa-ch/patterns-library pull request #1702
Opened 2020-03-24 16:31 UTC by raphaellueckl

Fixes #1693

# Done is when (DoD):
- [ ] Modifications within components are reflected by tests.
- [ ] A self-review of the code has been performed.
- [ ] The modified component properties have been added to the typescript typings.
- [ ] Potential design changes have been reviewed by a designer.
- [ ] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [ ] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [ ] The modifications are shortly added to CHANGELOG.md with the issue number.
- [ ] The modifications still work in IE.
- [ ] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

2020-03-25 19:02 UTC, markus-walther requested changes
What I reviewed is basically OK, just needing cleanup as indicated.

BUT: This is arguably incomplete, since the ticket asks for an _option_. In other words, the behaviour of margins is not conditioned on any attribute. I suggest either `margin` with numeric value (default: 0) or Boolean `noMargin`.

2020-03-25 19:02 UTC, markus-walther commented on src/components/10-atoms/heading/index.js
> +    <style>
Why use a `<style>` tag for this?? Put it into index.scss.

2020-03-25 19:02 UTC, markus-walther commented on src/components/10-atoms/heading/index.js
> +      :host {
`:host` is OK. It's already used for `<axa-icon>`.

2020-03-25 19:02 UTC, markus-walther commented on src/components/10-atoms/heading/index.js
> +        display: block;
Write a comment in the CSS why `display:block` is crucial, and the default for custom element doesn't work here.

2020-03-26 06:56 UTC, raphaellueckl commented on src/components/10-atoms/heading/index.js
> +    <style>
Yes, I will do that, if we decide to go with this approach. :)

2020-03-26 08:22 UTC, NoahLiechti commented on src/components/10-atoms/heading/story.js
> +      `;
I would use this in a demo, because the I think the slim overview of the different sizes is very helpful.

2020-03-26 14:24 UTC, closed without merging