Bugfix/table sortable datesortcolumnindex fix
axa-ch/patterns-library pull request #1767
Opened 2020-05-08 13:22 UTC by NoahLiechti

Fixes #(issue)

# Done is when (DoD):
- [ ] Modifications within components are reflected by tests.
- [ ] A self-review of the code has been performed.
- [ ] The modified component properties have been added to the typescript typings.
- [ ] Potential design changes have been reviewed by a designer.
- [ ] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [ ] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [ ] The modifications are shortly added to CHANGELOG.md with the issue number.
- [ ] The modifications still work in IE.
- [ ] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

2020-05-11 12:44 UTC, markus-walther requested changes
LGTM. Question: what's the specific part that was failing under React? I suggest to identify/explain with a comment so we can learn something reading your source code ;-)

2020-05-11 12:44 UTC, markus-walther commented on src/components/30-organisms/table-sortable/CHANGELOG.md
> +- `datesortcolumnindex` now works with react. #1765
Capitalize: React

2020-05-11 13:18 UTC, NoahLiechti commented on src/components/30-organisms/table-sortable/CHANGELOG.md
> +- `datesortcolumnindex` now works with react. #1765
Thank you!

2020-05-11 13:21 UTC, NoahLiechti commented
@markus-walther the problem was that the value of `dateSortColumnIndex` (`this.dateSortColumnIndex`) wasn't available in the constructor. The reason for that I didn't find out.

2020-05-12 11:06 UTC, danyball approved these changes
lgtm

2020-05-13 06:51 UTC, merged