Feature/1807 keyevents
axa-ch/patterns-library pull request #1833
Opened 2020-06-29 06:38 UTC by danyball

Fixes #1807 

# Done is when (DoD):
- [ ] Modifications within components are reflected by tests.
- [ ] A self-review of the code has been performed.
- [ ] The modified component properties have been added to the typescript typings.
- [ ] Potential design changes have been reviewed by a designer.
- [ ] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [ ] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [ ] The modifications are shortly added to CHANGELOG.md with the issue number.
- [ ] The modifications still work in IE.
- [ ] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

2020-06-29 11:58 UTC, 01231 requested changes

2020-06-29 11:58 UTC, NoahLiechti commented on src/components/20-molecules/datepicker/index.js
> +    this.handleInputKeyUp = this.handleInputKeyUp.bind(this);
Is there a reason for two different names?
I personally would name both handleInputKeyUp and onInputKeyUp or handleInputfieldKeyUp and onInputfieldKeyUp

2020-06-30 06:37 UTC, 01231 requested changes

2020-06-30 06:37 UTC, NoahLiechti commented on src/components/20-molecules/datepicker/react/DemoDatepickerOnInputfieldKeyUp.jsx
> +            e.key;
it's a little confusing just to see a letter above the input field without additional text. I would add some text like: `last typed letter: xy`

2020-06-30 07:28 UTC, raphaellueckl approved these changes
lgtm

2020-06-30 07:44 UTC, 01231 approved these changes
LGTM

2020-06-30 07:59 UTC, merged