Feature/component flat list
axa-ch/patterns-library pull request #1844
Opened 2020-07-02 06:13 UTC by NoahLiechti

Fixes #(issue)

# Done is when (DoD):
- [ ] Modifications within components are reflected by tests.
- [ ] A self-review of the code has been performed.
- [ ] The modified component properties have been added to the typescript typings.
- [ ] Potential design changes have been reviewed by a designer.
- [ ] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [ ] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [ ] The modifications are shortly added to CHANGELOG.md with the issue number.
- [ ] The modifications still work in IE.
- [ ] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

2020-07-06 06:58 UTC, raphaellueckl submitted a review, later dismissed
LGTM, but I don't like that all the "main stories" are now called "Story" instead of by their specific component name.

2020-07-06 07:19 UTC, danyball requested changes
- can you configure Storybook to always try to open "Story" if the user clicks on a folder? Maybe the word "story" is not understood by our users. Maybe something like "Example" or "Showcase" would be better?!

- is it possible to set the same icon on the components? It looks a little bumpy.
![image](https://user-images.githubusercontent.com/7448004/86566226-96299400-bf69-11ea-94db-b458530c2dff.png)

2020-07-06 07:19 UTC, danyball commented on .storybook/config.js
> +      a[1].kind === b[1].kind ? 0 : a[1].id.localeCompare(b[1].id, undefined, { numeric: true }),
nice!

2020-07-06 07:37 UTC, NoahLiechti commented
> * can you configure Storybook to always try to open "Story" if the user clicks on a folder? Maybe the word "story" is not understood by our users. Maybe something like "Example" or "Showcase" would be better?!
> * is it possible to set the same icon on the components? It looks a little bumpy.
>   ![image](https://user-images.githubusercontent.com/7448004/86566226-96299400-bf69-11ea-94db-b458530c2dff.png)

The folder icon appears when there are subfolders in the component and the blue one when there is no subfolder.
Storybook seems to only open a story automatically when there is no subfolder (blue icon). In the passt they all where blue and therefore opened the story on click.

2020-07-08 06:41 UTC, danyball commented
> > * can you configure Storybook to always try to open "Story" if the user clicks on a folder? Maybe the word "story" is not understood by our users. Maybe something like "Example" or "Showcase" would be better?!
> > * is it possible to set the same icon on the components? It looks a little bumpy.
> >   ![image](https://user-images.githubusercontent.com/7448004/86566226-96299400-bf69-11ea-94db-b458530c2dff.png)
> 
> * The folder icon appears when there are subfolders in the component and the blue one when there is no subfolder. The word examples or showcase are synonyms for demo in my opinion. Our stories are demos itself. The name story gives it a reason to be in this superordinate position from the demos.
> * Storybook seems to only open a story automatically when there is no subfolder (blue icon). In the passt they all where blue and therefore opened the story on click.

I dont like `story`. Our `demos` showing just special behaviour and are not "showcases" that shows all the cases of a component.

2020-07-08 07:53 UTC, NoahLiechti commented
> * this
<img width="377" alt="Screenshot 2020-07-08 at 09 39 08" src="https://user-images.githubusercontent.com/38284563/86891304-e7b75780-c0fe-11ea-9904-80c15fe9afc0.png">

It's called storybook. If we can expect from the user to now what a storybook is we can expect from him that he will understand what a story is. And if he doesn't now what a story is, he'll probably know it as soon as he clicks on the component, because this is the first thing that opens. And due the fact that story will be used throughout the whole storybook this will not be much of a challenge for him.

If you really don't like the name story I'll need a better suggestion, because the old naming was not good and redundant. What i don't like about "examples" or "showcase" is, that this would also work for all the demos in my opinion. I know we could also say that about the name "story". What about "Nativ component" or "native story"? This would descriptive and unambiguously.

2020-07-08 07:57 UTC, LucaMele commented
I personally prefer story for the reaosons Noah explained

2020-07-09 07:52 UTC, danyball approved these changes

2020-07-09 08:15 UTC, merged