Fix dependent-component versioning
axa-ch/patterns-library pull request #1884
Opened 2020-07-20 13:40 UTC by markus-walther

Fixes #1832.

2020-07-20 15:01 UTC, danyball commented
`const externalVersion = versionInfo[tagName];` --> versionInfo could be a string like "rsv". In this case something unexpected could happen.

2020-07-20 15:03 UTC, danyball commented
`componentClass.versions = externalVersion;` --> why save this variable at `.versions` of the class? Have removed this logic for a test and everything works?! Without that we can remove many lines of code.

2020-07-20 15:04 UTC, danyball requested changes
I am going to test the code and give u feedback....

2020-07-20 15:04 UTC, danyball commented on src/components/30-organisms/footer/index.js
> +    defineVersioned([AXAContainer], __VERSION_INFO__, this, this);
Search-replace error. this is doubled

2020-07-20 15:06 UTC, markus-walther commented on src/components/30-organisms/footer/index.js
> +    defineVersioned([AXAContainer], __VERSION_INFO__, this, this);
Good catch!

2020-07-20 15:11 UTC, markus-walther commented
> `const externalVersion = versionInfo[tagName];` --> versionInfo could be a string like "rsv". In this case something unexpected could happen.

('foo')['bar'] === undefined // true; welcome to the wonderfully bizarre world of JS... ;-)

2020-07-20 15:13 UTC, markus-walther commented
> `componentClass.versions = externalVersion;` --> why save this variable at `.versions` of the class? Have removed this logic for a test and everything works?! Without that we can remove many lines of code.

This is done for live debugging of a website, see https://github.com/axa-ch/patterns-library/blob/develop/COMPONENT_VERSIONING.md, paragraph about `automatic npm version`.

2020-07-21 06:13 UTC, danyball commented
> > `const externalVersion = versionInfo[tagName];` --> versionInfo could be a string like "rsv". In this case something unexpected could happen.
> 
> ('foo')['bar'] === undefined // true; welcome to the wonderfully bizarre world of JS... ;-)

Yes its working. But in this case its hard to understand why your code wants to select a key of a string. Its useless in this case. Why not add a if around?

2020-07-21 06:17 UTC, danyball commented
> > `componentClass.versions = externalVersion;` --> why save this variable at `.versions` of the class? Have removed this logic for a test and everything works?! Without that we can remove many lines of code.
> 
> This is done for live debugging of a website, see https://github.com/axa-ch/patterns-library/blob/develop/COMPONENT_VERSIONING.md, paragraph about `automatic npm version`.

Ah ok for debugging. I would add a comment at that line. (i wondered why you are doing this)

2020-07-21 06:18 UTC, danyball commented
It works - all my tests are working.

2020-07-21 13:05 UTC, danyball approved these changes

2020-07-21 13:21 UTC, merged