feature/1959_sanitize-sortable
axa-ch/patterns-library pull request #1983
Opened 2020-09-30 07:14 UTC by raphael-suter

Fixes #1959 

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Modifications still work in IE.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.

2020-10-05 09:23 UTC, NoahLiechti submitted a review, later dismissed
LGTM

2020-10-06 06:07 UTC, danyball requested changes
Pls add this new feature to the Readme.

2020-10-06 06:07 UTC, danyball commented on src/components/30-organisms/table-sortable/react/demo.jsx
> +      { text: '<span>22.04.2019</span>' },
It is not possible to sort this column. If you click on the header nothing happens. Pls have a look why.

2020-10-06 10:57 UTC, danyball approved these changes, later dismissed

2020-10-09 06:11 UTC, danyball approved these changes

2020-10-09 06:42 UTC, merged