feature/1998_fieldset-error-gap
axa-ch/patterns-library pull request #2000
Opened 2020-10-08 09:01 UTC by raphael-suter

Fixes #1998 

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Modifications still work in IE.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.

2020-10-09 06:29 UTC, danyball requested changes
The error message is not below the fieldset if you use "horizontal: stretch"

2020-10-09 06:47 UTC, NoahLiechti requested changes
please ignore this message

2020-10-09 06:56 UTC, NoahLiechti commented
> The error message is not below the fieldset if you use "horizontal: stretch"

It works for me.
<img width="935" alt="Screenshot 2020-10-09 at 08 55 39" src="https://user-images.githubusercontent.com/38284563/95552634-4eedec00-0a0d-11eb-9948-320823973b1a.png">
<img width="1220" alt="Screenshot 2020-10-09 at 08 54 58" src="https://user-images.githubusercontent.com/38284563/95552640-51504600-0a0d-11eb-9ff7-c9d2081cacfd.png">

2020-10-09 06:59 UTC, NoahLiechti commented on src/components/10-atoms/fieldset/index.scss
> +      margin: 11px 0 0 !important;
why 11px margin? In the code of the input-field I see a margin of 10px...

2020-10-09 07:04 UTC, NoahLiechti requested changes
Checkbox styling (with fieldset) now has changed due to the fieldset changes:(

New
<img width="742" alt="Screenshot 2020-10-09 at 08 45 54" src="https://user-images.githubusercontent.com/38284563/95553035-0aaf1b80-0a0e-11eb-930e-c83cf093173b.png">

Old
<img width="742" alt="Screenshot 2020-10-09 at 08 46 05" src="https://user-images.githubusercontent.com/38284563/95553031-097dee80-0a0e-11eb-9d09-b1417d41346f.png">

2020-10-09 09:00 UTC, NoahLiechti approved these changes
LGTM

2020-10-19 06:25 UTC, danyball approved these changes

2020-10-19 07:00 UTC, merged