Feature/remove datepicker width property
axa-ch/patterns-library pull request #2028
Opened 2020-11-10 09:10 UTC by NoahLiechti

Fixes #1894

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Modifications still work in IE.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2020-11-13 08:56 UTC, raphaellueckl requested changes

2020-11-13 08:56 UTC, raphaellueckl commented on src/components/20-molecules/datepicker/react/story.jsx
> +    const inlineWidth = text('width (not an attribute)', '');
What is this? Do we really need that?

2020-11-13 08:56 UTC, raphaellueckl commented on src/utils/with-react.js
> +        // {width: "500px"} -> width:500px;
When I see stuff like that, I usually think an extra method, that explains what it does with its name, makes the code more readable.

2020-11-13 08:56 UTC, raphaellueckl commented on src/components/20-molecules/datepicker/react/story.jsx
> +    const inlineWidth = text('width (not an attribute)', '');
IMHO we should not have that as a prop. This is just general styling and we would somehow have to add it for all other elements too.

2020-11-13 08:59 UTC, NoahLiechti commented on src/components/20-molecules/datepicker/react/story.jsx
> +    const inlineWidth = text('width (not an attribute)', '');
It's nice to have for demo purposes in my opinion. And it's a real use case. We expect the user to use this feature in the datepicker.

2020-11-13 09:02 UTC, NoahLiechti commented
seems like it doesn't work on ie

2020-11-13 10:16 UTC, raphaellueckl commented on src/components/20-molecules/datepicker/react/story.jsx
> +    const inlineWidth = text('width (not an attribute)', '');
A bit weird to me, but up to you.

2020-11-13 14:33 UTC, NoahLiechti commented on src/utils/with-react.js
> +        // {width: "500px"} -> width:500px;
done

2020-11-17 14:23 UTC, raphaellueckl approved these changes

2020-11-18 08:05 UTC, merged