Feature/pipeline fail on uncommitted files
axa-ch/patterns-library pull request #2122
Opened 2021-03-26 14:17 UTC by raphaellueckl

Fixes #2109

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Modifications still work in IE.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2021-03-29 05:49 UTC, danyball requested changes
i dont think this check can help. lerna is changing the lock files i think

2021-03-30 07:58 UTC, raphaellueckl commented
What do you mean? Lerna is also installing all of our components before testing it. And often, after `npm i`, there are some package-lock files that are not being committed. This makes sure that this does not happen.

2021-03-30 11:01 UTC, danyball commented
> What do you mean? Lerna is also installing all of our components before testing it. And often, after `npm i`, there are some package-lock files that are not being committed. This makes sure that this does not happen.

i have developed a new feature at materials. The version at package.json has been changed by lerna. (i choose major release). And after that, lerne updated all the package.jsons of components who are using materials.

2021-04-01 13:28 UTC, danyball approved these changes

2021-04-01 13:28 UTC, danyball commented on package.json
> +    "check-for-uncommitted-files": "git status && git diff-index --quiet HEAD --"
do you need the two "--" at the end?

2021-04-01 13:32 UTC, merged