Fix #2223: Reset File Upload possibility
axa-ch/patterns-library pull request #2227
Opened 2021-10-05 17:34 UTC by markus-walther

Fixes #2223.

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Modifications still work in IE.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2021-11-01 15:14 UTC, raphaellueckl requested changes

2021-11-01 15:14 UTC, raphaellueckl commented on src/components/20-molecules/file-upload/README.md
> +### reset
I would add this to a separate section, as this is not a property.

2021-11-01 17:33 UTC, markus-walther commented on src/components/20-molecules/file-upload/README.md
> +### reset
Done

2021-11-02 06:37 UTC, raphaellueckl approved these changes

2021-11-03 10:49 UTC, merged