Fix scripts on windows
axa-ch/patterns-library pull request #2281
Opened 2022-05-10 13:40 UTC by MKaHead

Fixes scripts on windows

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

2022-05-10 18:07 UTC, markus-walther requested changes
Hi Marco,

good work, just small issues to improve!

You may merge on your own without re-approval after you fixed them.

Cheers, Markus

2022-05-10 18:07 UTC, markus-walther commented on package.json
> +    "build": "cross-env NODE_ENV=production npm run build-components",
Good catch!

2022-05-10 18:07 UTC, markus-walther commented on package.json
> +    "test": "npm run test-lint && prettier --check . && node ./scripts/build.test.js && npm run test-ui",
I hope prettier checks recursively, like eslint?!

2022-05-10 18:07 UTC, markus-walther commented on scripts/build.test.js
> +  const { 2: category } = file.split('/');
This is super-hard to read!
Better: `const [_src, _components, category] = file.split('/');`

2022-05-10 18:07 UTC, markus-walther commented on scripts/build.test.js
> +  // file looks even on windows like that, thats why necessary hardcode the slash
Wording: ... that's why **it is** necessary **to** hard-code

2022-05-11 14:29 UTC, MKaHead commented on package.json
> +    "test": "npm run test-lint && prettier --check . && node ./scripts/build.test.js && npm run test-ui",
yes

2022-05-17 13:51 UTC, markus-walther approved these changes
All good now, Marco!

2022-05-17 13:51 UTC, markus-walther commented on scripts/build.test.js
> +  // file looks even on windows like that, that's why it is necessary to hard-code the slash
Good now!

2022-05-18 17:22 UTC, merged