Feature/webpack 5 sb web
axa-ch/patterns-library pull request #2282
Opened 2022-05-18 22:44 UTC by MKaHead

- Storybook 6.5
- Upgrade to webpack 5 and do migration
- Remove watchConfig polling: main reason for poor storybook performance under windows
- Use @storybook/web-components instead of html
- Use terser instead of uglify for dist build
- Remove hack to hide the new version banner instead use a flag
- Use main.js config to set static path for storybook
- Some more dependencies upgrades and remove obsolete packages

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2022-05-30 16:52 UTC, markus-walther requested changes
Hi Marco,

small findings only.

I am torn between wanting the flaky tests deleted, or commented out via multi-line comments, or left like you commented them out with single-line comments.

In general I think commenting out is the wrong tool for the job in the age of version-control systems.

Maybe compromise by adding a link to the conversion-to-Playwright issue (you didn't create it yet).

I leave it to you to make a reasoned decision here.

Rest is fine. Good work!

Markus

2022-05-30 16:52 UTC, markus-walther commented on .storybook/preview.js
> +// import '../src/components/05-utils/polyfill/index';
Don't comment out stuff, just delete it - it's the job of version-control systems (i.e. git for us) to recover old code from a previous version

2022-05-30 16:52 UTC, markus-walther commented on package.json
> +    "webpack": "^5.72.1"
good!

2022-05-30 16:52 UTC, markus-walther commented on scripts/build/dist.rollup.js
> +const { terser } = require('rollup-plugin-terser');
good!

2022-05-30 16:52 UTC, markus-walther commented on scripts/build/dist.rollup.js
>      babel({
one of the next PRs: get rid of babel!

2022-05-30 16:52 UTC, markus-walther commented on scripts/build/dist.rollup.js
> +      ecma: 5,
one of the next PRs: ES6!

2022-05-30 18:46 UTC, MKaHead commented
@markus-walther Create issue #2284 and delete flaky tests.

2022-05-31 10:08 UTC, markus-walther approved these changes
Marco,

good work indeed!

Playwright has delay functions, no need to do setTimeout thingies client-side. But you can clean that up in your footer test another PR.

Approved!

--Markus

2022-05-31 11:38 UTC, merged