Feature/accordion
axa-ch/patterns-library pull request #2303
Opened 2022-06-27 12:15 UTC by MKaHead

Should fix: #2290, #2279
- Rename Accordeon to Accordion that now a new component
- When the window is resized, the height of the container is recalculated and set in css
- Remove axa-text use styles for texts 
- Variant small now default instead of large -> see figma

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2022-06-28 12:50 UTC, markus-walther requested changes
Hi Marco,


great work! Some small findings only.

Would it be possible to add a Playwright test demonstrating that resizing works now?

Cheers, Markus

2022-06-28 12:50 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
> +    return 'axa-accordion';
This requires a **big fat warning** when announcing the new version on Slack's patterns-lib-devs!!! What if somebody has baked the old name into his app?

Also, we need to release as semver major version.

2022-06-28 12:50 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
> +      large: { type: Boolean },
Another backwards-incompatible change = double reason for big fat warning.

2022-06-28 12:50 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
> +    this.debouncedHandleViewportCheck = debounce(this.toggleAnimation, 500);
Requires a comment saying what problem is solved here by debouncing and explaining the magical 500 milliseconds!

2022-06-28 12:50 UTC, markus-walther commented on src/components/20-molecules/accordion/package.json
> +  "version": "1.0.0",
Ah, I see. You are treating it as a new npm package. That would work ;-)

Can we then mark @axa-ch/accordeon as deprecated on npm? If needed, by publishinhg 3.0.1 with big fat deprecation warning?

2022-06-28 12:50 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
> +    this.debouncedHandleViewportCheck = debounce(this.toggleAnimation, 500);
this.debouncedHandleViewportCheck is not a great name. That it's debounced can be inspected locally at the method, it's a minor detail.

How about this.recalculateDimensionsOnResize?

2022-06-28 12:54 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
> +              <span class="${classMap(titleClasses)}">${title}</span>
much leaner, I like it :-)

2022-06-29 12:10 UTC, MKaHead commented on src/components/20-molecules/accordion/package.json
> +  "version": "1.0.0",
We can do this easily on npm. [see here](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions)

2022-06-30 14:57 UTC, markus-walther requested changes
Hi Marco,

almost there - 2 tiny things, and you're good.

You can self-approve after that.

--Markus

2022-06-30 14:57 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
> +    this.recalculateDimensionsOnResize = debounce(this.toggleAnimation, 500);
// See https://bencentra.com/code/2015/02/27/optimizing-window-resize.html for why we debounce here.

2022-06-30 14:57 UTC, markus-walther commented on src/components/20-molecules/accordion/index.js
>      if (this.open) {
While youre' at it, you might as well DRYify it more here:

`accordionContent.style.maxHeight = this.open ? `${accordionContent.scrollHeight}px` : 0;`

2022-06-30 14:57 UTC, markus-walther commented on src/components/20-molecules/accordion/package.json
> +  "version": "1.0.0",
Learned something new, great!

2022-07-04 08:24 UTC, markus-walther approved these changes
Hi Marco,

LGTM.

--Markus

2022-07-04 08:47 UTC, merged