Feature/storybook controls
axa-ch/patterns-library pull request #2313
Opened 2022-07-25 07:14 UTC by MKaHead

Migration of storybook knobs for controls
- Using the latest API and args
- Remove redundant code
- Optimize stories
- Changes of story names
- Adjustment of test files

Disadvantages:
- I had to remove some tests because they are not yet compatible with storybook controls. What doesn't work yet escapeHTML: false this will probably come with the next version.
- Some tests were not compatible and just go beyond the scope of the migration and have to be rebuilt afterwards.

Findings General:
What are good tests? There is simply an incredible redundant amount of tests. We should fundamentally rethink how tests are written.

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2022-07-25 16:51 UTC, markus-walther requested changes
Dear Marco,

a ton of good work - a challenge to review, of course, due to the bulk changes you had to make.

Few things that caught my eye, try to do the best with them....

Keep up the good work, Markus

2022-07-25 16:51 UTC, markus-walther commented on .storybook/preview.js
> +      { name: 'red', value: '#f00' },
Why these 3 colours? And what does it do?

2022-07-25 16:51 UTC, markus-walther commented on scripts/create-a-m-o/functions.js
> +    import { args, argTypes } from './story.args';
Nice that you updated the component generator!

2022-07-25 16:51 UTC, markus-walther commented on scripts/create-a-m-o/functions.js
> +    export const ${compTitle} = ({ slot }) => html\`<axa-${fileName}>\${slot}</axa-${fileName}>\`;`,
Nice, much easier!

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/checkbox/demo.js
> +    error="This checkbox do not have a label, but its also clickable"
Grammar: .... do**es** not have a label, but **it's still** clickable

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/input-text/react/story.jsx
> +  // activate the Safari's autocomplete feature.
grammar: activate Safari's autocomplete feature (**no _the_**)

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/input-text/react/story.jsx
> +/* TODO rewrite this
What does that mean here?

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/textarea/demo.js
> +/* TODO rewrite this
This looks ugly, commented-out stuff should not be retained - version control takes care of earlier revisions, not comments.

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/textarea/react/DemoControlledUncontrolledTextarea.jsx
> +const DemoControlledUncontrolledTextarea = () => {
Very confusing name. `DemoControllabilityOfTextarea` perhaps?

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/textarea/react/demo.jsx
> +import DemoControlledUncontrolledTextarea from './DemoControlledUncontrolledTextarea';
see above for naming

2022-07-25 16:51 UTC, markus-walther commented on src/components/10-atoms/textarea/react/demo.jsx
> +export const TextareaControlledUncontrolled = () =>
see above for naming

2022-07-25 16:51 UTC, markus-walther commented on src/utils/create-react-container.jsx
> +export function createReactContainer(
why function? My default would have been to use arrow function wherever possible...

2022-07-25 16:51 UTC, markus-walther commented on src/utils/render-lit-container.js
> +export function renderLitContainer(
ditto

2022-07-26 08:33 UTC, MKaHead commented on .storybook/preview.js
> +      { name: 'red', value: '#f00' },
For example, there are components that have a variant where their background becomes white. Then the problem is that you can't see the component at all. Some stories had functionality to switch background. With the change I remove redundancies and provide further uniformity.

2022-07-26 12:09 UTC, markus-walther commented on .storybook/preview.js
> +      { name: 'red', value: '#f00' },
I see, that's OK.

2022-07-26 15:13 UTC, merged