Fix axa top content bar props declaration
axa-ch/patterns-library pull request #2449
Opened 2023-06-16 12:19 UTC by Pachj

Fixes #
Fix type declaration for AXATopContentBarProps.

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

2023-06-16 13:28 UTC, FreiLoris submitted a review, later dismissed
LGTM

2023-06-21 09:21 UTC, FreiLoris approved these changes, later dismissed
LGTM

2023-06-22 12:31 UTC, marcwelz requested changes
Documentation is not up to Date, please add description to the new variants in the readme.md
File: src\components\20-molecules\top-content-bar\README.md

Please note for future Pull requests: Please link the github issue to the pr description. 

Thanks for your work.

2023-06-23 12:21 UTC, marcwelz approved these changes
LGTM

2023-06-23 12:48 UTC, merged